(function(a){var e={UNDEFINED:0,BUILDED:1,LOADED:2,INITED:3},f=this;if("undefined"!=typeof module)module.exports=exports=f={},f.Z=f;var d={},c={},b=0,g=function(b){if(d[b])return d[b];var b=b.split("."),g=f,c;for(c in b){if(!(b[c]in g))return a;g=g[b[c]]}return g},h=function(b){return(b=g(b))?b.packageStatus:e.UNDEFINED},p=function(b,a,h){"string"===typeof b&&(b=g(b));var f={},d=g("Z");if(a)for(var i in a)f[i]=g(a[i]);h&&h.call(b,d,f);b.packageStatus=e.INITED;b=b.packageName;if(a=c[b]){for(f=0;f<
a.length;f++)h=a[f],k(h.requirePackages)&&p(h.packageName,h.requirePackages,h.constructor);delete c[b]}},k=function(b){if(!b)return!0;var a,g;for(g in b)if(a=b[g],h(a)!==e.INITED)return!1;return!0},i=function(){var a,g,h;a=arguments[0];3===arguments.length?(g=arguments[1],h=arguments[2]):2===arguments.length?h=arguments[1]:(a="Z.anonymous."+b++,h=arguments[0]);var i;i=a;var l=d[i];if(!l){var l=f,o=i.split("."),q;for(q in o)o[q]in l||(l[o[q]]={}),l=l[o[q]];d[i]=l}if(!("packageName"in l))l.packageName=
i;if(!("packageStatus"in l))l.packageStatus=e.BUILDED;i=l;if(i.packageStatus===e.BUILDED)i.packageStatus=e.LOADED;if(g&&!k(g))for(var s in g)l=g[s],c[l]||(c[l]=[]),c[l].push({packageName:a,requirePackages:g,constructor:h});else p(i,g,h);return i};Z=i("Z",function(b){b.PACKAGE_STATUS=e;b.$package=i;b.getPackage=g;b.getPackageStatus=h})})();
Z.$package("Z.array",function(){this.remove=function(a,e,f){var d=!1;if(2===arguments.length){var c=a.indexOf(e);-1!==c&&(a.splice(c,1),d=!0)}else for(var c=0,b=a.length;c<b;c++)if(a[c][e]===f){a.splice(c,1);d=!0;break}return d};this.filter=function(a,e,f){var d=[],c;for(c in a)a[c][e]===f&&d.push(a[c]);return d};this.contains=function(a,e){return-1<a.indexOf(e)};this.uniquelize=function(a){for(var e=[],f=0,d=a.length;f<d;f++)this.contains(e,a[f])||e.push(a[f]);return e};this.parse=function(a){return Array.prototype.slice.call(a)};
this.forEach=function(a,e,f){var d=null;if(!this.isArray(a))if(this.isObject(a)){var d=[],c;for(c in a)a.hasOwnProperty(c)&&d.push(c)}else throw Error("not an array or a object");var b=-1,g=(d||a).length,h=function(){if(++b>=g)f&&f(g);else{var c=d?d[b]:b;e&&e(a[c],c,h)}};h()}});
Z.$package("Z",function(a){this.debug=function(b){"undefined"!=typeof console&&(console.debug?console.debug(b):console.log(b))};var e=Object.prototype.toString;this.is=function(b,a){var h=e.call(a).slice(8,-1);return void 0!==a&&null!==a&&h===b};this.isString=function(b){return"[object String]"===e.call(b)};this.isArray=Array.isArray||function(b){return"[object Array]"===e.call(b)};this.isArguments=function(b){return"[object Arguments]"===e.call(b)};this.isObject=function(b){return"[object Object]"===
e.call(b)};this.isFunction=function(b){return"[object Function]"===e.call(b)};this.isUndefined=function(b){return"[object Undefined]"===e.call(b)};this.isBoolean=function(b){return"[object Boolean]"===e.call(b)};this.isNumber=function(b){return"[object Number]"===e.call(b)};this.isEmpty=function(b){if(b){if(this.isArray(b))return!!b.length;for(var a in b)return!1;return!0}return!1};var f=this.isSameObject=function(b,g,h){if(b===g||!b&&!g)return!0;for(var c in b)if(b.hasOwnProperty(c))if(a.isObject(b[c])&&
a.isObject(g[c])&&h){if(!f(b[c],g[c],h))return!1}else if(b[c]!==g[c])return!1;return!0},d=function(b,c,h){for(var f=arguments,e,i=1;i<f.length;i++){e=f[i];for(var j in e)b[j]=a.isArray(e[j])?e[j].concat():a.isObject(e[j])?b[j]&&a.isArray(b[j])?d({},e[j]):d({},b[j],e[j]):e[j]}return b},c=function(b){if(a.isArray(b))return b.concat();if(a.isArguments(b)){for(var g=[],h=0,f;f=b[h];h++)g.push(c(f));return g}return a.isObject(b)?d({},b):b};this.merge=d;this.duplicate=c;this.extend=function(b,a){b.prototype=
d({},a.prototype,b.prototype);b.prototype.constructor=b}});
Z.$package("Z.browser",function(a){var e=this;(function(){var a={set:function(b,a){this.name=b;this.version=a;this[b]=a}},b,g=navigator.userAgent.toLowerCase();(b=g.match(/msie ([\d.]+)/))?a.set("ie",b[1]):(b=g.match(/firefox\/([\d.]+)/))?a.set("firefox",b[1]):(b=g.match(/chrome\/([\d.]+)/))?a.set("chrome",b[1]):(b=g.match(/opera.([\d.]+)/))?a.set("opera",b[1]):(b=g.match(/version\/([\d.]+).*safari/))&&a.set("safari",b[1]);Z.merge(e,a)})();var f={ie:"Ms",firefox:"Moz",opera:"O",chrome:"Webkit",safari:"Webkit"},
d;this.cssSupport=function(c,b,g){var h;d||(d=document.createElement("div"));h=d;if(c in h.style)return h.style[c]=b,h.style[c]===b;return g?(g=c.charAt(0).toUpperCase(),c=f[a.browser.name]+g+c.substr(1),cssSupport(c,!1,b)):!1}});
Z.$package("Z",function(a){var e=function(){},f=/this.\$super/,d=function(b,c){1===arguments.length&&(c=b,b={});c=c||{};if(!a.isFunction(c.init))c.init=e;var d=function(){return this.init.apply(this,arguments)},k=b.extend;if(k){if("interface"===k.type&&a.isArray(k.methods)&&a.isFunction(k.checkImplements))throw Error("can not extend a interface!");var i=k.prototype.init,j=c.init,m=a.duplicate(k.prototype);delete m.init;var k=d.prototype=a.merge({},k.prototype,c),n,r,l;for(l in m)n=k[l],r=m[l],a.isFunction(r)&&
a.isFunction(n)&&f.test(n)&&(k[l]=function(b,a){return function(){var c=this.$super;this.$super=b;a.apply(this,arguments);this.$super=c}}(r,n));d.prototype.init=function(){var b=a.duplicate(arguments);i.apply(this,b);this.$static=d;j.apply(this,arguments)}}else j=c.init,d.prototype=c,d.prototype.init=function(){this.$static=d;j.apply(this,arguments)};d.prototype.constructor=d;d.type="class";d.className=b.name||"anonymous";if(m=b["implements"]){l=[];for(var o in m)k=m[o].checkImplements(d.prototype),
l=l.concat(k);if(l.length)throw Error("the '"+d.className+"' class hasn't implemented the interfaces's methods . ["+l+"]");}b.statics&&a.merge(d,b.statics);return d},c=function(b){var c=[],f,d;for(d in this.methods)f=b[this.methods[d]],(!f||!a.isFunction(f))&&c.push(methods[d]);return c},b=function(b,a){1===arguments.length&&(a=b,b={});var f=function(){throw Error("the interface can not be Instantiated!");};f.type="interface";f.interfaceName=b.name||"anonymous";f.methods=a;f.checkImplements=c;return f};
this.define=function(a,c,f){var e=Array.prototype.slice.call(arguments,1);if("class"===a)return d.apply(this,e);if("interface"===a)return b.apply(this,e)};this.$class=d;this.$interface=b});
Z.$package("Z.cookie",function(a){var e=window.location.host;this.set=function(f,d,c,b,g){if(g){var h=new Date;h.setTime(+new Date+36E5*g)}a.isString(d)||(d=JSON.stringify(d));d=window.encodeURIComponent(d);window.document.cookie=f+"="+d+"; "+(g?"expires="+h.toGMTString()+"; ":"")+(b?"path="+b+"; ":"path=/; ")+(c?"domain="+c+";":"domain="+e+";")};this.get=function(a){a=window.document.cookie.match(RegExp("(?:^|;+|\\s+)"+a+"=([^;]*)"));a=!a?"":a[1];a=window.decodeURIComponent(a);try{a=JSON.parse(a)}catch(d){}return a};
this.remove=function(a,d,c){window.document.cookie=a+"=; expires=Mon, 26 Jul 1997 05:00:00 GMT; "+(c?"path="+c+"; ":"path=/; ")+(d?"domain="+d+";":"domain="+e+";")}});
Z.$package("Z.date",function(){this.format=function(a,e){var f={"M+":a.getMonth()+1,"d+":a.getDate(),"h+":a.getHours(),"m+":a.getMinutes(),"s+":a.getSeconds(),"q+":Math.floor((a.getMonth()+3)/3),S:a.getMilliseconds()};/(y+)/.test(e)&&(e=e.replace(RegExp.$1,(a.getFullYear()+"").substr(4-RegExp.$1.length)));for(var d in f)RegExp("("+d+")").test(e)&&(e=e.replace(RegExp.$1,1==RegExp.$1.length?f[d]:("00"+f[d]).substr((""+f[d]).length)));return e}});
Z.$package("Z.file",function(a){this.ImageLoader=a.$class({init:function(){this._imageList={}},load:function(a,f,d){var c=this._imageList[a];c||(c={url:a,status:0,cbs:[]},this._imageList[a]=c);if(2===c.status)f.call(d||window,!0,a,c.size);else if(1===c.status)c.cbs.push({cb:f,cxt:d});else{c.cbs.push({cb:f,cxt:d});c.status=1;var f=new Image,b=this;f.onload=function(){var a=b._imageList[this.src];a.status=2;a.size={width:this.width,height:this.height};for(var c=0,d;d=a.cbs[c];c++)d.cb.call(d.cxt||window,
!0,a.url,a.size);a.cbs=[]};d=function(){var a=b._imageList[this.src];a.status=3;for(var c=0,d;d=a.cbs[c];c++)d.cb.call(d.cxt||window,!1,a.url);a.cbs=[]};f.onerror=d;f.onabort=d;f.src=a}}})});
Z.$package("Z.message",function(a){var e,f=0,d=function(){if(!e&&(e=document.createElement("div"),!document.createEvent))e.style.cssText="position: absolute; top: -9999em; left: -9999em; width: 0px; height: 0px;",document.body.appendChild(e);return e},c=function(b,c,e,k){var i,j,m,n;if(2>arguments.length)throw Error("addListener arguments not enough");a.isString(b)&&(k=e,e=c,c=b,b=window);k||(k=window);if(!b.__listeners)b.__listeners={},b.__listenerId=+new Date+""+f++;m=b.__listeners;n=b.__listenerId;
if(m[c])for(j in m[c]){if(i=m[c][j],i.func===e)return!1}else m[c]=[];j=d();j.addEventListener?(i=function(a){e.apply(k,a.params);k=null},j.addEventListener(n+"-"+c,i,!1)):(i=function(a){var a=window.event,b=a.params.pop();c===a.params[1]&&b===n&&(e.apply(k,a.params),k=null)},j.attachEvent("onpropertychange",i));i={func:e,wrapFunc:i};m[c].push(i);return!0},b=function(a,b,c){var f,e,j,m;if(2>arguments.length)throw Error("removeListener arguments not enough");2===arguments.length&&(c=b,b=a,a=window);
j=a.__listeners;m=a.__listenerId;if(!j||!j[b])return!1;e=d();for(var n in j[b])if(f=j[b][n],f.func===c)return j[b].slice(n,1),e.removeEventListener?e.removeEventListener(m+"-"+b,f.wrapFunc,!1):e.detachEvent("onpropertychange",f.wrapFunc),!0;return!1};this.on=this.addListener=c;this.off=this.removeListener=b;this.notify=function(b,c,f){var e,i,j,m;1===arguments.length?(c=b,b=window):2===arguments.length&&a.isString(b)&&(f=c,c=b,b=window);a.debug("notify message: "+c);j=b.__listeners;m=b.__listenerId;
if(!j||!j[c])return!1;e=d();document.createEvent?(i=document.createEvent("Events"),i.initEvent(m+"-"+c,!1,!1),i.params=[f,c],e.dispatchEvent(i)):(i=document.createEventObject("onpropertychange"),i.params=[f,c,m],e.fireEvent("onpropertychange",i));return 0!==j[c].length}});
Z.$package("Z.number",function(){this.format=function(a,e){for(var f=a.toString().split("."),d=e?e.split("."):[""],c="",b=f[0],g=d[0],h=b.length-1,p=!1,k=g.length-1;0<=k;k--)switch(g.substr(k,1)){case "#":0<=h&&(c=b.substr(h--,1)+c);break;case "0":c=0<=h?b.substr(h--,1)+c:"0"+c;break;case ",":p=!0,c=","+c}if(0<=h)if(p)for(g=b.length;0<=h;h--)c=b.substr(h,1)+c,0<h&&0==(g-h)%3&&(c=","+c);else c=b.substr(0,h+1)+c;c+=".";b=1<f.length?f[1]:"";g=1<d.length?d[1]:"";for(k=h=0;k<g.length;k++)switch(g.substr(k,
1)){case "#":h<b.length&&(c+=b.substr(h++,1));break;case "0":c=h<b.length?c+b.substr(h++,1):c+"0"}return c.replace(/^,+/,"").replace(/\.$/,"")};this.getMaxMin=function(a){var e=0,f=0,d=a.length;if(0<d)for(var f=a[0],c=0;c<d;c++)a[c]>e?e=a[c]:a[c]<f&&(f=a[c]);return{max:e,min:f}};this.random=function(a,e){return Math.floor(Math.random()*(e-a+1)+a)}});
Z.$package("Z.storage",function(a){var e=a.$class({name:"Storage"},{init:function(a){this._storage=a},isSupport:function(){return null!=this._storage},set:function(f,d){return this.isSupport()?(a.isString(d)||(d=JSON.stringify(d)),this._storage.setItem(f,d),!0):!1},get:function(a){if(this.isSupport()){a=this._storage.getItem(a);try{a=JSON.parse(a)}catch(d){}return a}return!1},remove:function(a){return this.isSupport()?(this._storage.removeItem(a),!0):!1},clear:function(){return this.isSupport()?(this._storage.clear(),
!0):!1}});this.local=new e(window.localStorage);this.session=new e(window.sessionStorage)});
Z.$package("Z.string",function(){this.toQueryString=function(a){var e=[],f;for(f in a)e.push(encodeURIComponent(""+f)+"="+encodeURIComponent(""+a[f]));return e.join("&")};this.format=function(a,e,f){if(0==arguments.length)return null;for(var a=arguments[0],d=1;d<arguments.length;d++)a=a.replace(RegExp("\\{"+(d-1)+"\\}","gm"),arguments[d]);return a};this.sizeof=function(a,e){var f=0,d,c,b,e=e?e.toLowerCase():"";if("utf-16"===e||"utf16"===e)for(c=0,b=a.length;c<b;c++)d=a.charCodeAt(c),f=65535>=d?f+
2:f+4;else for(c=0,b=a.length;c<b;c++)d=a.charCodeAt(c),f=127>=d?f+1:2047>=d?f+2:65535>=d?f+3:f+4;return f};this.isEmpty=function(a){return null==a||""==a?!0:!1};this.capital=function(a){return this.isEmpty(a)?"":a.charAt(0).toUpperCase()+a.substring(1)};this.endsWith=function(a,e){return a.lastIndexOf(e)+e.length==a.length}});
