(function(c){var a={UNDEFINED:0,BUILDED:1,LOADED:2,INITED:3},b={},e={},d=function(a){if(b[a])return b[a];var a=a.split("."),d=window,e;for(e in a){if(!(a[e]in d))return c;d=d[a[e]]}return d},f=function(b){return(b=d(b))?b.packageStatus:a.UNDEFINED},h=function(b,c,f){"string"===typeof b&&(b=d(b));var g={},n=d("Z");if(c)for(var o in c)g[o]=d(c[o]);f&&f.call(b,n,g);b.packageStatus=a.INITED;b=b.packageName;if(c=e[b]){for(g=0;g<c.length;g++)f=c[g],i(f.requirePackages)&&h(f.packageName,f.requirePackages,
f.constructor);delete e[b]}},i=function(b){if(!b)return!0;var d,e;for(e in b)if(d=b[e],f(d)!==a.INITED)return!1;return!0},g=function(){var d,c,f;d=arguments[0];3===arguments.length?(c=arguments[1],f=arguments[2]):f=arguments[1];var g;g=b[d];if(!g){g=window;var n=d.split("."),o;for(o in n)n[o]in g||(g[n[o]]={}),g=g[n[o]];b[d]=g}if(!("packageName"in g))g.packageName=d;if(!("packageStatus"in g))g.packageStatus=a.BUILDED;if(g.packageStatus===a.BUILDED)g.packageStatus=a.LOADED;if(c&&!i(c))for(var p in c)g=
c[p],e[g]||(e[g]=[]),e[g].push({packageName:d,requirePackages:c,constructor:f});else h(g,c,f)};g("Z",function(b){b.PACKAGE_STATUS=a;b.$package=g;b.getPackage=d;b.getPackageStatus=f})})();
Z.$package("Z.array",function(){this.remove=function(c,a,b){var e=!1;if(2===arguments.length){var d=c.indexOf(a);-1!==d&&(c.splice(d,1),e=!0)}else for(var d=0,f=c.length;d<f;d++)if(c[d][a]===b){c.splice(d,1);e=!0;break}return e};this.filter=function(c,a,b){var e=[],d;for(d in c)c[d][a]===b&&e.push(c[d]);return e};this.contains=function(c,a){return-1<c.indexOf(a)};this.uniquelize=function(c){for(var a=[],b=0,e=c.length;b<e;b++)this.contains(a,c[b])||a.push(c[b]);return a};this.parse=function(c){return Array.prototype.slice.call(c)}});
Z.$package("Z",function(c){this.debug=function(a){window.console&&(console.debug?console.debug(a):console.log(a))};var a=Object.prototype.toString;this.is=function(b,e){var c=a.call(e).slice(8,-1);return void 0!==e&&null!==e&&c===b};this.isString=function(b){return"[object String]"===a.call(b)};this.isArray=Array.isArray||function(b){return"[object Array]"===a.call(b)};this.isArguments=function(b){return"[object Arguments]"===a.call(b)};this.isObject=function(b){return"[object Object]"===a.call(b)};
this.isFunction=function(b){return"[object Function]"===a.call(b)};this.isUndefined=function(b){return"[object Undefined]"===a.call(b)};this.isEmpty=function(b){if(b){if(this.isArray(b))return!!b.length;for(var a in b)return!1;return!0}return!1};var b=function(a,e,h){for(var i=arguments,g,l=1;l<i.length;l++){g=i[l];for(var j in g)a[j]=c.isArray(g[j])?g[j].concat():c.isObject(g[j])?a[j]&&c.isArray(a[j])?b({},g[j]):b({},a[j],g[j]):g[j]}return a},e=function(a){if(c.isArray(a))return a.concat();if(c.isArguments(a)){for(var f=
[],h=0,i;i=a[h];h++)f.push(e(i));return f}if(c.isObject(a))return b({},a);throw Error("the argument isn't an object or array");};this.merge=b;this.duplicate=e;this.extend=function(a,e){b(a,e);a.prototype=b({},e.prototype,a.prototype)}});
Z.$package("Z.browser",function(c){var a=this;(function(){var b={set:function(b,a){this.name=b;this.version=a;this[b]=a}},e,c=navigator.userAgent.toLowerCase();(e=c.match(/msie ([\d.]+)/))?b.set("ie",e[1]):(e=c.match(/firefox\/([\d.]+)/))?b.set("firefox",e[1]):(e=c.match(/chrome\/([\d.]+)/))?b.set("chrome",e[1]):(e=c.match(/opera.([\d.]+)/))?b.set("opera",e[1]):(e=c.match(/version\/([\d.]+).*safari/))&&b.set("safari",e[1]);Z.merge(a,b)})();var b={ie:"Ms",firefox:"Moz",opera:"O",chrome:"Webkit",safari:"Webkit"},
e;this.cssSupport=function(a,f,h){var i;e||(e=document.createElement("div"));i=e;if(a in i.style)return i.style[a]=f,i.style[a]===f;return h?(h=a.charAt(0).toUpperCase(),a=b[c.browser.name]+h+a.substr(1),cssSupport(a,!1,f)):!1}});
Z.$package("Z",function(c){var a=function(){},b=function(b,e){1===arguments.length&&(e=b,b={});e=e||{};if(!c.isFunction(e.init))e.init=a;var d=function(){return this.init.apply(this,arguments)},g=b.extend;if(g){if("interface"===g.type&&c.isArray(g.methods)&&c.isFunction(g.checkImplements))throw Error("can not extend a interface!");var l=g.prototype.init,j=e.init,k=c.duplicate(g.prototype);delete k.init;var g=d.prototype=c.merge({},g.prototype,e),m;for(m in k)c.isFunction(k[m])&&c.isFunction(g[m])&&
(g[m]=function(b,a){return function(){var e=this.$super;this.$super=b;a.apply(this,arguments);this.$super=e}}(k[m],g[m]));d.prototype.init=function(){var b=c.duplicate(arguments);l.apply(this,b);this.$static=d;b=c.duplicate(arguments);j.apply(this,b)}}else j=e.init,d.prototype=e,d.prototype.init=function(){this.$static=d;j.apply(this,arguments)};d.prototype.constructor=d;d.type="class";d.className=b.name||"anonymous";if(k=b["implements"]){m=[];for(var n in k)g=k[n].checkImplements(d.prototype),m=
m.concat(g);if(m.length)throw Error("the '"+d.className+"' class hasn't implemented the interfaces's methods . ["+m+"]");}b.statics&&c.merge(d,b.statics);return d},e=function(b){var a=[],e,d;for(d in this.methods)e=b[this.methods[d]],(!e||!c.isFunction(e))&&a.push(methods[d]);return a},d=function(b,a){1===arguments.length&&(a=b,b={});var d=function(){throw Error("the interface can not be Instantiated!");};d.type="interface";d.interfaceName=b.name||"anonymous";d.methods=a;d.checkImplements=e;return d};
this.define=function(a,e,c){var g=Array.prototype.slice.call(arguments,1);if("class"===a)return b.apply(this,g);if("interface"===a)return d.apply(this,g)};this.$class=b;this.$interface=d});
Z.$package("Z.cookie",function(c){var a=window.location.host;this.set=function(b,e,d,f,h){if(h){var i=new Date;i.setTime(+new Date+36E5*h)}c.isString(e)||(e=JSON.stringify(e));e=window.encodeURIComponent(e);window.document.cookie=b+"="+e+"; "+(h?"expires="+i.toGMTString()+"; ":"")+(f?"path="+f+"; ":"path=/; ")+(d?"domain="+d+";":"domain="+a+";")};this.get=function(b){b=window.document.cookie.match(RegExp("(?:^|;+|\\s+)"+b+"=([^;]*)"));b=!b?"":b[1];b=window.decodeURIComponent(b);try{b=JSON.parse(b)}catch(a){}return b};
this.remove=function(b,e,d){window.document.cookie=b+"=; expires=Mon, 26 Jul 1997 05:00:00 GMT; "+(d?"path="+d+"; ":"path=/; ")+(e?"domain="+e+";":"domain="+a+";")}});
Z.$package("Z.date",function(){this.format=function(c,a){var b={"M+":c.getMonth()+1,"d+":c.getDate(),"h+":c.getHours(),"m+":c.getMinutes(),"s+":c.getSeconds(),"q+":Math.floor((c.getMonth()+3)/3),S:c.getMilliseconds()};/(y+)/.test(a)&&(a=a.replace(RegExp.$1,(c.getFullYear()+"").substr(4-RegExp.$1.length)));for(var e in b)RegExp("("+e+")").test(a)&&(a=a.replace(RegExp.$1,1==RegExp.$1.length?b[e]:("00"+b[e]).substr((""+b[e]).length)));return a}});
Z.$package("Z.dom",function(){this.ellipsis=function(c,a){var b=c.clientWidth,a=a||"…",e=c.cloneNode(!0);e.id="checkTextLengthNode";e.style.cssText="position: absolute;left: -99999em;width: auto !important;";c.parentNode.appendChild(e);if(!(e.clientWidth<=b)){e.innerHTML=a;for(var d=e.clientWidth,f=c.innerHTML,f=f.replace(/\s+/g," "),h,i=0,g=0,l=f.length;g<l;g++)if(h=f.charAt(g),e.innerHTML=" "===h?"&nbsp;":h,i+=e.clientWidth,i+d>b){f=f.substr(0,g);break}c.innerHTML=f+a;e.parentNode.removeChild(e)}}});
Z.$package("Z.dom",["Z.string"],function(c){var a=this;this.get=function(b){return document.getElementById(b)};var b={};this.getTemplate=function(a){var d=b[a];if(!d){var c=this.get(a),d=c.innerHTML;c.parentNode.removeChild(c);b[a]=d}if(!d)throw Error('no such template. [id="'+a+'"]');return d};this.getActionTarget=function(b,a,c,h){for(var b=b.target,i=a||3,a=-1!==a,c=c||"cmd",h=h||document.body;b&&b!==h&&(a?0<i--:1);){if(b.getAttribute(c))return b;b=b.parentNode}return null};this.render=function(b,
a,f,h){f=f||{};a=this.getTemplate(a);a=c.string.template(a,f);"string"===typeof b&&(b=this.get(b));if(!c.isUndefined(h)&&b.childElementCount){f=document.createElement("div");f.innerHTML=a;for(var a=f.children,i=document.createDocumentFragment();a[0];)i.appendChild(a[0]);-1===h||h>=b.childElementCount-1?b.appendChild(i):b.insertBefore(i,b.children[h]);delete f}else b.innerHTML=a};this.bindCommends=function(b,d,f){1===arguments.length?(f=b,b=document.body,d="click"):2===arguments.length&&(f=d,d="click");
b.__commends?c.merge(b.__commends,f):(b.__commends=f,b.addEventListener(d,function(b){var e=a.getActionTarget(b,3,"cmd",this);if(e){var d=e.getAttribute("cmd"),c=e.getAttribute("param");e.href&&0===e.getAttribute("href").indexOf("#")&&b.preventDefault();if(this.__commends[d])this.__commends[d](c,e,b)}}))};this.isVisible=function(b,a,c){return c?0<=b.offsetTop-a.scrollTop&&b.offsetTop+b.clientHeight-a.scrollTop<=a.clientHeight?!0:!1:0<b.offsetTop+b.clientHeight-a.scrollTop&&b.offsetTop-a.scrollTop<
a.clientHeight?!0:!1}});
Z.$package("Z.message",function(c){var a,b=0,e=function(){if(!a&&(a=document.createElement("div"),!document.createEvent))a.style.cssText="position: absolute; top: -9999em; left: -9999em; width: 0px; height: 0px;",document.body.appendChild(a);return a},d=function(a,c,d){var f,j,k,m;if(2>arguments.length)throw Error("addListener arguments not enough");2===arguments.length&&(d=c,c=a,a=window);if(!a.__listeners)a.__listeners={},a.__listenerId=+new Date+""+b++;k=a.__listeners;m=a.__listenerId;if(k[c])for(j in k[c]){if(f=
k[c][j],f.func===d)return!1}else k[c]=[];j=e();j.addEventListener?(f=function(b){d.apply(window,b.params)},j.addEventListener(m+"-"+c,f,!1)):(f=function(b){var b=window.event,a=b.params.pop();c===b.params[1]&&a===m&&d.apply(window,b.params)},j.attachEvent("onpropertychange",f));f={func:d,wrapFunc:f};k[c].push(f);return!0},f=function(b,a,c){var d,f,k,m;if(2>arguments.length)throw Error("removeListener arguments not enough");2===arguments.length&&(c=a,a=b,b=window);k=b.__listeners;m=b.__listenerId;
if(!k||!k[a])return!1;f=e();for(var n in k[a])if(d=k[a][n],d.func===c)return k[a].slice(n,1),f.removeEventListener?f.removeEventListener(m+"-"+a,d.wrapFunc,!1):f.detachEvent("onpropertychange",d.wrapFunc),!0;return!1};this.on=this.addListener=d;this.off=this.removeListener=f;this.notify=function(b,a,d){var f,j,k,m;1===arguments.length?(a=b,b=window):2===arguments.length&&c.isString(b)&&(d=a,a=b,b=window);c.debug("notify message: "+a);k=b.__listeners;m=b.__listenerId;if(!k||!k[a])return!1;f=e();document.createEvent?
(j=document.createEvent("Events"),j.initEvent(m+"-"+a,!1,!1),j.params=[d,a],f.dispatchEvent(j)):(j=document.createEventObject("onpropertychange"),j.params=[d,a,m],f.fireEvent("onpropertychange",j));return 0!==k[a].length}});
Z.$package("Z.number",function(){this.format=function(c,a){for(var b=c.toString().split("."),e=a?a.split("."):[""],d="",f=b[0],h=e[0],i=f.length-1,g=!1,l=h.length-1;0<=l;l--)switch(h.substr(l,1)){case "#":0<=i&&(d=f.substr(i--,1)+d);break;case "0":d=0<=i?f.substr(i--,1)+d:"0"+d;break;case ",":g=!0,d=","+d}if(0<=i)if(g)for(h=f.length;0<=i;i--)d=f.substr(i,1)+d,0<i&&0==(h-i)%3&&(d=","+d);else d=f.substr(0,i+1)+d;d+=".";f=1<b.length?b[1]:"";h=1<e.length?e[1]:"";for(l=i=0;l<h.length;l++)switch(h.substr(l,
1)){case "#":i<f.length&&(d+=f.substr(i++,1));break;case "0":d=i<f.length?d+f.substr(i++,1):d+"0"}return d.replace(/^,+/,"").replace(/\.$/,"")};this.getMaxMin=function(c){var a=0,b=0,e=c.length;if(0<e)for(var b=c[0],d=0;d<e;d++)c[d]>a?a=c[d]:c[d]<b&&(b=c[d]);return{max:a,min:b}};this.random=function(c,a){return Math.ceil(Math.random()*(a-c)+c)}});
Z.$package("Z.storage",function(c){var a=c.$class({name:"Storage"},{init:function(b){this._storage=b},isSupport:function(){return null!=this._storage},set:function(b,a){return this.isSupport()?(c.isString(a)||(a=JSON.stringify(a)),this._storage.setItem(b,a),!0):!1},get:function(b){if(this.isSupport()){b=this._storage.getItem(b);try{b=JSON.parse(b)}catch(a){}return b}return!1},remove:function(b){return this.isSupport()?(this._storage.removeItem(b),!0):!1},clear:function(){return this.isSupport()?(this._storage.clear(),
!0):!1}});this.local=new a(window.localStorage);this.session=new a(window.sessionStorage)});
Z.$package("Z.string",function(){this.toQueryString=function(b){var a=[],c;for(c in b)a.push(encodeURIComponent(""+c)+"="+encodeURIComponent(""+b[c]));return a.join("&")};var c={},a=this.template=function(b,e){var d=!/\W/.test(b)?c[b]=c[b]||a(document.getElementById(b).innerHTML):new Function("obj","var z_tmp=[],print=function(){z_tmp.push.apply(z_tmp,arguments);};with(obj){z_tmp.push('"+b.replace(/[\r\t\n]/g," ").split("<%").join("\t").replace(/((^|%>)[^\t]*)'/g,"$1\r").replace(/\t=(.*?)%>/g,"',$1,'").split("\t").join("');").split("%>").join("z_tmp.push('").split("\r").join("\\'")+
"');}return z_tmp.join('');");return e?d(e):d};this.format=function(a,c,d){if(0==arguments.length)return null;for(var a=arguments[0],f=1;f<arguments.length;f++)a=a.replace(RegExp("\\{"+(f-1)+"\\}","gm"),arguments[f]);return a}});
Z.$package("Z.ui",["Z.util"],function(c){this.ScrollAction=c.define("class",{init:function(a){this._id="scroll_action_"+(a.id||a.element.getAttribute("id"));this._el=a.element;this._step=a.step||50;this._animationDuration=a.animationDuration||10;this._scrollEventDelay=a.scrollEventDelay||200;this._onScrollToBottom=a.onScrollToBottom;this._onScrollToTop=a.onScrollToTop;this._onAnimationStart=a.onAnimationStart;this._onAnimationEnd=a.onAnimationEnd;var b=this;this._el.addEventListener("scroll",function(){c.util.delay(b._id+
"_scroll",b._scrollEventDelay+b._animationDuration,function(){b._noScollEvent?b._noScollEvent=!1:b.isTop()&&b._onScrollToTop?b._onScrollToTop():b.isBottom()&&b._onScrollToBottom&&b._onScrollToBottom()})},!1)},getScrollTop:function(){return this._el.scrollTop},isTop:function(){return 0===this._el.scrollTop},isBottom:function(){return this._el.scrollTop===this._el.scrollHeight-this._el.clientHeight},setAnimation:function(a,b){if(a)this._step=a;if(b)this._animationDuration=b},scrollTo:function(a,b,e){var d=
this;c.util.clearLoop(this._id);var f=this._el.scrollHeight-this._el.clientHeight;c.isString(a)&&("top"===a&&(a=0),"bottom"===a&&(a=f));0>a&&(a=0);a>f&&(a=f);if(a===this._el.scrollTop)return!1;this._noScollEvent=e;if(b){var h=d._el.scrollTop,i=a,g=0<i-h?1:-1,l=!1;c.util.loop(this._id,this._animationDuration,function(){l||(l=!0,d._onAnimationStart&&d._onAnimationStart());h+=g*d._step;var a=!1;if(0<g&&h>i||0>g&&h<i)h=i,a=!0,c.util.clearLoop(d._id);d._el.scrollTop=h;a&&d._onAnimationEnd&&d._onAnimationEnd()})}else this._el.scrollTop=
a;return!0}})});
Z.$package("Z.util",["Z.message"],function(c){this.Beater=c.$class({name:"Beater",statics:{DEFAULT_INTERVAL:50,DEFAULT_MAX_INTERVAL:6E4}},{init:function(a){a=a||{};this._triggers={};this._beaters={};this._isStart=!1;this._autoStart="autoStart"in a?a.autoStart:!0;this._interval=a.interval||this.$static.DEFAULT_INTERVAL;this._maxInterval=a.maxInterval||this.$static.DEFAULT_MAX_INTERVAL},checkBeater:function(){var a=0,b;for(b in this._beaters)a+=this._beaters[b];return!!a},add:function(a,b,e){if(b%this._interval)b=
Math.round(b/this._interval)*this._interval;else if(b<this._interval)b=this._interval;else if(b>this._maxInterval)b=this._maxInterval;if(this._triggers[a])throw Error("beater is exist");this._beaters[b]=this._beaters[b]||0;this._triggers[a]={time:b,func:e};c.message.on(this,"Beater-"+b,e);this._beaters[b]++;!this._isStart&&this._autoStart&&this.start();return!0},remove:function(a){var b=this._triggers[a];if(!b)return!1;var e="Beater-"+b.time;this._beaters[b.time]--;this._triggers[a]=null;delete this._triggers[a];
c.message.off(this,e,b.func);this.checkBeater()||this.stop();return!0},start:function(){if(this._isStart)return!1;var a=this,b=0,e=this._interval;this._timer=setInterval(function(){b+=e;b>=a._maxInterval&&(b=0);var d,f;for(f in a._beaters)a._beaters[f]&&(d=Number(f),b%d||c.message.notify(a,"Beater-"+d,{time:d}))},e);return this._isStart=!0},stop:function(){if(!this._isStart)return!1;clearInterval(this._timer);this._timer=0;this._isStart=!1;return!0}})});
Z.$package("Z.util",["Z.message","Z.array"],function(c){this.Collection=new c.$class({name:"Collection"},{init:function(a){function b(){e.setModify()}a=a||{};this._keyName=a.keyName||"id";this._arr=[];this._map={};this._modifyTime=0;var e=this;c.message.on(this,"add",b);c.message.on(this,"remove",b);c.message.on(this,"clear",b);c.message.on(this,"update",b)},setModify:function(){this._modifyTime=+new Date},getModify:function(){return this._modifyTime},getByKey:function(a){return this.get(a)},getByIndex:function(a){return this.index(a)},
getIndexByKey:function(a,b){b=b||this._keyName;if(this._map[a])for(var c in this._arr)if(this._arr[c][b]==a)return c;return null},getKeyByIndex:function(a,b){var b=b||this._keyName,c=this.getByIndex(a);return c?c[b]:null},get:function(a){return this._map[a]},index:function(a){return this._arr[a]},getRange:function(a,b){return this._arr.slice(a,a+b)},filter:function(a,b){return c.array.filter(this._arr,a,b)},add:function(a,b,e){if(this._map[a[this._keyName]])return!1;this._map[a[this._keyName]]=a;
c.isUndefined(b)?(b=this._arr.length,this._arr.push(a)):this._arr.splice(b,0,a);e||c.message.notify(this,"add",{items:[a],index:b});return a},addRange:function(a,b,e){var d=[],f,h=this._keyName,i;for(i in a)f=a[i],this._map[f[h]]||(d.push(f),this._map[f[h]]=f);if(!d.length)return!1;c.isUndefined(b)?(b=this._arr.length,this._arr=this._arr.concat(d)):(a=[b,0].concat(d),Array.prototype.splice.apply(this._arr,a));e||c.message.notify(this,"add",{items:d,index:b});return d},removeByKey:function(a,b){var e=
this._map[a];if(e){var d=this.getIndexByKey(a);this._arr.splice(d,1);delete this._map[a];b||c.message.notify(this,"remove",{items:[e],index:d,key:a});return e}return!1},removeByIndex:function(a,b){var e=this._arr[a];return e?(this._arr.splice(a,1),delete this._map[e[this._keyName]],b||c.message.notify(this,"remove",{items:[e],index:a,key:e[this._keyName]}),e):!1},remove:function(a){return this.removeByKey(a)},removeRange:function(a,b){var e=[],d,f=this._keyName,h;for(h in a)d=a[h],this.removeByKey(d[f],
!0)&&e.push(d);if(!e.length)return!1;b||c.message.notify(this,"remove",{items:e});return e},update:function(a,b){var e=this.get(a.id);return e?(c.merge(e,a),b||c.message.notify(this,"update",{items:[e]}),e):!1},updateRange:function(a){var b=[],e,d;for(d in a)(e=this.update(a[d],!0))&&b.push(e);b.length&&c.message.notify(this,"update",{items:[b]});return!1},length:function(){return this._arr.length},clear:function(a){var b=this._arr;this._arr=[];this._map={};a||c.message.notify(this,"clear",{items:b})},
getFirst:function(){return this.index(0)},getLast:function(){return this.index(this.length()-1)},getAll:function(){return this.getRange(0,this.length())},each:function(a){for(var b=0,c;c=this._arr[b];b++)a(c,b)},exist:function(a){return!!this.get(a)}})});
Z.$package("Z.util",function(c){this.DependentQueue=new c.$class({name:"DependentQueue",statics:{STATUS_INIT:1,STATUS_RUNNING:2,STATUS_PAUSE:3,STATUS_STOP:4}},{init:function(a){a=a||{};this._onFinish=a.onFinish;this._onPause=a.onPause;this._onStop=a.onStop;this._currentIndex=-1;this._items=[];this._status=this.$static.STATUS_INIT},add:function(a){if(this.isRunning())return!1;this._items.push(a);return!0},isRunning:function(){return this._status===this.$static.STATUS_RUNNING},run:function(){if(this.isRunning()||
0>=this._items.length||this._currentIndex>=this._items.length-1)return!1;this._status=this.$static.STATUS_RUNNING;this.next()},reRun:function(){this._currentIndex--;this.next()},next:function(){this._currentIndex++;var a=this._items[this._currentIndex];a?a.exec(this,a):this._onFinish&&this._onFinish(this)},pause:function(){this._status=this.$static.STATUS_PAUSE;this._onPause&&this._onPause(this,this._items[this._currentIndex])},stop:function(){this._status=this.$static.STATUS_STOP;this._onStop&&this._onStop(this,
this._items[this._currentIndex])}})});
Z.$package("Z.util",["Z.message","Z.string","Z.util"],function(c){this.HttpRequest=new c.$class({init:function(a){this._require=a.require;this._requestCollection=new c.util.Collection({keyName:"id"})},require:function(a,b,e){var d=c.string.toQueryString(b.data),f;f=-1==a.indexOf("?")?a+"?"+d:a+"&"+d;var e=e||{},h=b.onSuccess,i=b.onError,g=b.onTimeout;if(d=this._requestCollection.get(f)){if("loading"===d.status)return!1;if(e.cacheTime&&d.responseTime-d.requireTime<e.cacheTime)return a=b.context||window,
h&&h.call(a,d.response),!0;this._requestCollection.remove(f)}var l={id:f,param:b,requireTime:+new Date,status:"loading"};this._requestCollection.add(l);b.onSuccess=function(a){e.cacheTime?(l.responseTime=+new Date,l.status="loaded",l.response=a):this._requestCollection.remove(f);var c=b.context||window;h&&h.call(c,a)};b.onError=function(a){this._requestCollection.remove(f);var c=b.context||window;i&&i.call(c,a)};b.onTimeout=function(a){this._requestCollection.remove(f);var c=b.context||window;g&&
g.call(c,a)};this._require(a,b)}})});Z.$package("Z.util",function(){this.debounce=function(c,a,b){var e;return function(){if(!e||+new Date-e>c)b?a():setTimeout(a,c),e=+new Date}}});
Z.$package("Z.util",function(){var c={};this.delay=function(a,b,e,d){var f=arguments,h=0;1===f.length?(e=a,b=0,a=null):2===f.length&&(e=b,b=a,a=null);b=b||0;a&&b?(a in c&&(window.clearTimeout(c[a]),h=1),f=window.setTimeout(function(){c[a]=0;delete c[a];e.apply(d||window,[a])},b),c[a]=f):d?window.setTimeout(function(){e.apply(d||window)},b):window.setTimeout(e,b);return h};this.clearDelay=function(a){return a in c?(window.clearTimeout(c[a]),c[a]=0,delete c[a],0):2}});
Z.$package("Z.util",function(c){var a=Object.prototype.hasOwnProperty;this.sizeof=function(b){if(c.isArray(b))return b.length;var e,d=0;for(e in b)a.call(b,e)&&d++;return d}});
Z.$package("Z.util",function(){var c={};this.loop=function(a,b,e,d){var f=0;2==arguments.length&&(e=b,b=a);b=b||0;if(a&&b){a in c&&(window.clearInterval(c[a]),f=1);var h=window.setInterval(function(){e.apply(d||window,[a])},b);c[a]=h}else setInterval(e,b);return f};this.clearLoop=function(a){return a in c?(window.clearInterval(c[a]),c[a]=0,delete c[a],0):2}});
Z.$package("Z.util",function(c){this.timeTaken=function(a){var b=">>>",e,d;2===arguments.length?"function"===typeof arguments[1]?d=arguments[1]:b='"'+arguments[1]+'"':3===arguments.length&&(e=arguments[1],d=arguments[2]);c.debug(b+" time test start.");e&&e();e=+new Date;a();e=+new Date-e;d&&d(e);c.debug(b+" time test end. time taken: "+e)}});
