(function(c){var a={UNDEFINED:0,BUILDED:1,LOADED:2,INITED:3},b={},d={},e=function(){},f=function(a){if(b[a])return b[a];var a=a.split("."),d=window,e;for(e in a){if(!(a[e]in d))return c;d=d[a[e]]}return d},g=function(b){return(b=f(b))?b.packageStatus:a.UNDEFINED},h=function(b,e,c){"string"===typeof b&&(b=f(b));var g={},j=f("Z");if(e)for(var o in e)g[o]=f(e[o]);c&&c.call(b,j,g);b.packageStatus=a.INITED;b=b.packageName;if(e=d[b]){for(g=0;g<e.length;g++)c=e[g],k(c.requirePackages)&&h(c.packageName,c.requirePackages,
c.constructor);delete d[b]}},k=function(b){if(!b)return!0;var d,e;for(e in b)if(d=b[e],g(d)!==a.INITED)return!1;return!0},j=function(){var e,c,f;e=arguments[0];3===arguments.length?(c=arguments[1],f=arguments[2]):f=arguments[1];var g;g=b[e];if(!g){g=window;var j=e.split("."),o;for(o in j)j[o]in g||(g[j[o]]={}),g=g[j[o]];b[e]=g}if(!("packageName"in g))g.packageName=e;if(!("packageStatus"in g))g.packageStatus=a.BUILDED;if(g.packageStatus===a.BUILDED)g.packageStatus=a.LOADED;if(c&&!k(c))for(var q in c)g=
c[q],d[g]||(d[g]=[]),d[g].push({packageName:e,requirePackages:c,constructor:f});else h(g,c,f)};j("Z",function(b){b.debug=e;b.PACKAGE_STATUS=a;b.$package=j;b.getPackage=f;b.getPackageStatus=g})})();
Z.$package("Z",function(){var c=Object.prototype.toString;this.isString=function(a){return"[object String]"===c.call(a)};this.isArray=Array.isArray||function(a){return"[object Array]"===c.call(a)};this.isArguments=function(a){return"[object Arguments]"===c.call(a)};this.isObject=function(a){return"[object Object]"===c.call(a)};this.isFunction=function(a){return"[object Function]"===c.call(a)};this.isUndefined=function(a){return"[object Undefined]"===c.call(a)}});
Z.$package("Z",function(c){var a=function(){},b=function(a,d,e){for(var f=arguments,g,h=1;h<f.length;h++){g=f[h];for(var l in g)a[l]=c.isArray(g[l])?g[l].concat():c.isObject(g[l])?a[l]&&c.isArray(a[l])?b({},g[l]):b({},a[l],g[l]):g[l]}return a},d=function(a){if(c.isArray(a))return a.concat();if(c.isArguments(a)){for(var e=[],g=0,f;f=a[g];g++)e.push(d(f));return e}if(c.isObject(a))return b({},a);throw Error("the argument isn't an object or array");},e=function(){return this.className},f=function(g,
f){1===arguments.length&&(f=g,g={});f=f||{};if(!c.isFunction(f.init))f.init=a;var h=function(){c.debug("class ["+h.className+"] init");return this.init.apply(this,arguments)},i=g.extend;if(i){if("interface"===i.type&&c.isArray(i.methods)&&c.isFunction(i.checkImplements))throw Error("can not extend a interface!");var n=i.prototype.init,p=f.init,l=d(i.prototype);delete l.init;h.prototype=b({},i.prototype,f);var o=f;h.prototype.init=function(){var a=d(arguments);n.apply(this,a);this.$static=h;a=d(arguments);
p.apply(this,a);var b=this;this.$super={};for(var e in l)c.isFunction(l[e])&&o[e]&&(this.$super[e]=function(a){return function(){l[a].apply(b,arguments)}}(e))}}else p=f.init,h.prototype=f,h.prototype.init=function(){this.$static=h;p.apply(this,arguments)};h.type="class";h.className=g.name||"anonymous";h.toString=e;if(i=g["implements"]){var q=[],r,s;for(s in i)r=i[s].checkImplements(h.prototype),q=q.concat(r);if(q.length)throw Error("the '"+h.className+"' class hasn't implemented the interfaces's methods . ["+
q+"]");}g.statics&&b(h,g.statics);return h},g=function(a){var b=[],d,e;for(e in this.methods)d=a[this.methods[e]],(!d||!c.isFunction(d))&&b.push(methods[e]);return b},h=function(a,b){1===arguments.length&&(b=a,a={});var d=function(){throw Error("the interface can not be Instantiated!");};d.type="interface";d.interfaceName=a.name||"anonymous";d.methods=b;d.checkImplements=g;return d};this.merge=b;this.duplicate=d;this.define=function(a,b,d){var e=Array.prototype.slice.call(arguments,1);if("class"===
a)return f.apply(this,e);if("interface"===a)return h.apply(this,e)};this.$class=f;this.$interface=h});
Z.$package("Z.message",function(c){var a,b=0,d=function(){if(!a&&(a=document.createElement("div"),!document.createEvent))a.style.cssText="position: absolute; top: -9999em; left: -9999em; width: 0px; height: 0px;",document.body.appendChild(a);return a},e=function(a,e,c){var f,m,i,n;if(2>arguments.length)throw Error("addListener arguments not enough");2===arguments.length&&(c=e,e=a,a=window);if(!a.__listeners)a.__listeners={},a.__listenerId=+new Date+""+b++;i=a.__listeners;n=a.__listenerId;if(i[e])for(m in i[e]){if(f=
i[e][m],f.func===c)return!1}else i[e]=[];m=d();m.addEventListener?(f=function(a){c.apply(window,a.params)},m.addEventListener(n+"-"+e,f,!1)):(f=function(a){var a=window.event,b=a.params.pop();e===a.params[1]&&b===n&&c.apply(window,a.params)},m.attachEvent("onpropertychange",f));f={func:c,wrapFunc:f};i[e].push(f);return!0},f=function(a,b,e){var c,f,i,n;if(2>arguments.length)throw Error("removeListener arguments not enough");2===arguments.length&&(e=b,b=a,a=window);i=a.__listeners;n=a.__listenerId;
if(!i||!i[b])return!1;f=d();for(var p in i[b])if(c=i[b][p],c.func===e)return i[b].slice(p,1),f.removeEventListener?f.removeEventListener(n+"-"+b,c.wrapFunc,!1):f.detachEvent("onpropertychange",c.wrapFunc),!0;return!1};this.on=this.addListener=e;this.off=this.removeListener=f;this.notify=function(a,b,e){var f,m,i,n;1===arguments.length?(b=a,a=window):2===arguments.length&&c.isString(a)&&(e=b,b=a,a=window);c.debug("notify message: "+b);i=a.__listeners;n=a.__listenerId;if(!i||!i[b])return!1;f=d();document.createEvent?
(m=document.createEvent("Events"),m.initEvent(n+"-"+b,!1,!1),m.params=[e,b],f.dispatchEvent(m)):(m=document.createEventObject("onpropertychange"),m.params=[e,b,n],f.fireEvent("onpropertychange",m));return 0!==i[b].length}});
Z.$package("Z.array",function(){this.remove=function(c,a,b){var d=!1;if(2===arguments.length){var e=c.indexOf(a);-1!==e&&(c.splice(e,1),d=!0)}else for(var e=0,f=c.length;e<f;e++)if(c[e][a]===b){c.splice(e,1);d=!0;break}return d};this.filter=function(c,a,b){var d=[],e;for(e in c)c[e][a]===b&&d.push(c[e]);return d};this.contains=function(c,a){return-1<c.indexOf(a)};this.uniquelize=function(c){for(var a=[],b=0,d=c.length;b<d;b++)this.contains(a,c[b])||a.push(c[b]);return a};this.parse=function(c){return Array.prototype.slice.call(c)}});
Z.$package("Z.browser",function(c){var a=this;(function(){var b={set:function(a,b){this.name=a;this.version=b;this[a]=b}},d,c=navigator.userAgent.toLowerCase();(d=c.match(/msie ([\d.]+)/))?b.set("ie",d[1]):(d=c.match(/firefox\/([\d.]+)/))?b.set("firefox",d[1]):(d=c.match(/chrome\/([\d.]+)/))?b.set("chrome",d[1]):(d=c.match(/opera.([\d.]+)/))?b.set("opera",d[1]):(d=c.match(/version\/([\d.]+).*safari/))&&b.set("safari",d[1]);Z.merge(a,b)})();var b={ie:"Ms",firefox:"Moz",opera:"O",chrome:"Webkit",safari:"Webkit"},
d;this.cssSupport=function(a,f,g){var h;d||(d=document.createElement("div"));h=d;if(a in h.style)return h.style[a]=f,h.style[a]===f;return g?(g=a.charAt(0).toUpperCase(),a=b[c.browser.name]+g+a.substr(1),cssSupport(a,!1,f)):!1}});
Z.$package("Z.cookie",function(c){var a=window.location.host;this.set=function(b,d,e,f,g){if(g){var h=new Date;h.setTime(+new Date+36E5*g)}c.isString(d)||(d=JSON.stringify(d));d=window.encodeURIComponent(d);window.document.cookie=b+"="+d+"; "+(g?"expires="+h.toGMTString()+"; ":"")+(f?"path="+f+"; ":"path=/; ")+(e?"domain="+e+";":"domain="+a+";")};this.get=function(a){a=window.document.cookie.match(RegExp("(?:^|;+|\\s+)"+a+"=([^;]*)"));a=!a?"":a[1];a=window.decodeURIComponent(a);try{a=JSON.parse(a)}catch(d){}return a};
this.remove=function(b,d,e){window.document.cookie=b+"=; expires=Mon, 26 Jul 1997 05:00:00 GMT; "+(e?"path="+e+"; ":"path=/; ")+(d?"domain="+d+";":"domain="+a+";")}});
Z.$package("Z.date",function(){this.format=function(c,a){var b={"M+":c.getMonth()+1,"d+":c.getDate(),"h+":c.getHours(),"m+":c.getMinutes(),"s+":c.getSeconds(),"q+":Math.floor((c.getMonth()+3)/3),S:c.getMilliseconds()};/(y+)/.test(a)&&(a=a.replace(RegExp.$1,(c.getFullYear()+"").substr(4-RegExp.$1.length)));for(var d in b)RegExp("("+d+")").test(a)&&(a=a.replace(RegExp.$1,1==RegExp.$1.length?b[d]:("00"+b[d]).substr((""+b[d]).length)));return a}});
Z.$package("Z.dom",function(){this.ellipsis=function(c,a){var b=c.clientWidth,a=a||"…",d=c.cloneNode(!0);d.id="checkTextLengthNode";d.style.cssText="position: absolute;left: -99999em;width: auto !important;";c.parentNode.appendChild(d);if(!(d.clientWidth<=b)){d.innerHTML=a;for(var e=d.clientWidth,f=c.innerHTML,f=f.replace(/\s+/g," "),g,h=0,k=0,j=f.length;k<j;k++)if(g=f.charAt(k),d.innerHTML=" "===g?"&nbsp;":g,h+=d.clientWidth,h+e>b){f=f.substr(0,k);break}c.innerHTML=f+a;d.parentNode.removeChild(d)}}});
Z.$package("Z.dom",["Z.string"],function(c){var a=this;this.get=function(a){return document.getElementById(a)};var b={};this.getTemplate=function(a){var e=b[a];if(!e){var c=this.get(a),e=c.innerHTML;c.parentNode.removeChild(c);b[a]=e}if(!e)throw Error('no such template. [id="'+a+'"]');return e};this.getActionTarget=function(a,b,c,g){for(var a=a.target,h=b||3,b=-1!==b,c=c||"cmd",g=g||document.body;a&&a!==g&&(b?0<h--:1);){if(a.getAttribute(c))return a;a=a.parentNode}return null};this.render=function(a,
b,f,g){f=f||{};b=this.getTemplate(b);b=c.string.template(b,f);"string"===typeof a&&(a=this.get(a));if(!c.isUndefined(g)&&a.childElementCount){f=document.createElement("div");f.innerHTML=b;for(var b=f.children,h=document.createDocumentFragment();b[0];)h.appendChild(b[0]);-1===g||g>=a.childElementCount-1?a.appendChild(h):a.insertBefore(h,a.children[g]);delete f}else a.innerHTML=b};this.bindCommends=function(b,e,f){1===arguments.length?(f=b,b=document.body,e="click"):2===arguments.length&&(f=e,e="click");
b.__commends?c.merge(b.__commends,f):(b.__commends=f,b.addEventListener(e,function(b){var d=a.getActionTarget(b,3,"cmd",this);if(d){var c=d.getAttribute("cmd"),e=d.getAttribute("param");d.href&&0===d.getAttribute("href").indexOf("#")&&b.preventDefault();if(this.__commends[c])this.__commends[c](e,d,b)}}))};this.isVisible=function(a,b,c){return c?0<=a.offsetTop-b.scrollTop&&a.offsetTop+a.clientHeight-b.scrollTop<=b.clientHeight?!0:!1:0<a.offsetTop+a.clientHeight-b.scrollTop&&a.offsetTop-b.scrollTop<
b.clientHeight?!0:!1}});
Z.$package("Z.number",function(){this.format=function(c,a){for(var b=c.toString().split("."),d=a?a.split("."):[""],e="",f=b[0],g=d[0],h=f.length-1,k=!1,j=g.length-1;0<=j;j--)switch(g.substr(j,1)){case "#":0<=h&&(e=f.substr(h--,1)+e);break;case "0":e=0<=h?f.substr(h--,1)+e:"0"+e;break;case ",":k=!0,e=","+e}if(0<=h)if(k)for(g=f.length;0<=h;h--)e=f.substr(h,1)+e,0<h&&0==(g-h)%3&&(e=","+e);else e=f.substr(0,h+1)+e;e+=".";f=1<b.length?b[1]:"";g=1<d.length?d[1]:"";for(j=h=0;j<g.length;j++)switch(g.substr(j,1)){case "#":h<
f.length&&(e+=f.substr(h++,1));break;case "0":e=h<f.length?e+f.substr(h++,1):e+"0"}return e.replace(/^,+/,"").replace(/\.$/,"")};this.getMaxMin=function(c){var a=0,b=0,d=c.length;if(0<d)for(var b=c[0],e=0;e<d;e++)c[e]>a?a=c[e]:c[e]<b&&(b=c[e]);return{max:a,min:b}};this.random=function(c,a){return Math.ceil(Math.random()*(a-c)+c)}});
Z.$package("Z.storage",function(c){var a=c.$class({name:"Storage"},{init:function(a){this._storage=a},isSupport:function(){return null!=this._storage},set:function(a,d){return this.isSupport()?(c.isString(d)||(d=JSON.stringify(d)),this._storage.setItem(a,d),!0):!1},get:function(a){if(this.isSupport()){a=this._storage.getItem(a);try{a=JSON.parse(a)}catch(d){}return a}return!1},remove:function(a){return this.isSupport()?(this._storage.removeItem(a),!0):!1},clear:function(){return this.isSupport()?(this._storage.clear(),
!0):!1}});this.local=new a(window.localStorage);this.session=new a(window.sessionStorage)});
Z.$package("Z.string",function(){this.toQueryString=function(a){var d=[],c;for(c in a)d.push(encodeURIComponent(""+c)+"="+encodeURIComponent(""+a[c]));return d.join("&")};var c={},a=this.template=function(b,d){var e=!/\W/.test(b)?c[b]=c[b]||a(document.getElementById(b).innerHTML):new Function("obj","var z_tmp=[],print=function(){z_tmp.push.apply(z_tmp,arguments);};with(obj){z_tmp.push('"+b.replace(/[\r\t\n]/g," ").split("<%").join("\t").replace(/((^|%>)[^\t]*)'/g,"$1\r").replace(/\t=(.*?)%>/g,"',$1,'").split("\t").join("');").split("%>").join("z_tmp.push('").split("\r").join("\\'")+
"');}return z_tmp.join('');");return d?e(d):e};this.format=function(a,c,e){if(0==arguments.length)return null;for(var a=arguments[0],f=1;f<arguments.length;f++)a=a.replace(RegExp("\\{"+(f-1)+"\\}","gm"),arguments[f]);return a}});
Z.$package("Z.ui",["Z.util"],function(c){this.ScrollAction=c.define("class",{init:function(a){this._id="scroll_action_"+(a.id||a.element.getAttribute("id"));this._el=a.element;this._step=a.step||50;this._animationDuration=a.animationDuration||10;this._scrollEventDelay=a.scrollEventDelay||200;this._onScrollToBottom=a.onScrollToBottom;this._onScrollToTop=a.onScrollToTop;this._onAnimationStart=a.onAnimationStart;this._onAnimationEnd=a.onAnimationEnd;var b=this;this._el.addEventListener("scroll",function(){c.util.delay(b._id+
"_scroll",b._scrollEventDelay+b._animationDuration,function(){b._noScollEvent?b._noScollEvent=!1:b.isTop()&&b._onScrollToTop?b._onScrollToTop():b.isBottom()&&b._onScrollToBottom&&b._onScrollToBottom()})},!1)},getScrollTop:function(){return this._el.scrollTop},isTop:function(){return 0===this._el.scrollTop},isBottom:function(){return this._el.scrollTop===this._el.scrollHeight-this._el.clientHeight},setAnimation:function(a,b){if(a)this._step=a;if(b)this._animationDuration=b},scrollTo:function(a,b,d){var e=
this;c.util.clearLoop(this._id);var f=this._el.scrollHeight-this._el.clientHeight;c.isString(a)&&("top"===a&&(a=0),"bottom"===a&&(a=f));0>a&&(a=0);a>f&&(a=f);if(a===this._el.scrollTop)return!1;this._noScollEvent=d;if(b){var g=e._el.scrollTop,h=a,k=0<h-g?1:-1,j=!1;c.util.loop(this._id,this._animationDuration,function(){j||(j=!0,e._onAnimationStart&&e._onAnimationStart());g+=k*e._step;var a=!1;if(0<k&&g>h||0>k&&g<h)g=h,a=!0,c.util.clearLoop(e._id);e._el.scrollTop=g;a&&e._onAnimationEnd&&e._onAnimationEnd()})}else this._el.scrollTop=
a;return!0}})});
Z.$package("Z.util",["Z.message"],function(c){this.Beater=c.$class({name:"Beater",statics:{DEFAULT_INTERVAL:50,DEFAULT_MAX_INTERVAL:6E4}},{init:function(a){a=a||{};this._triggers={};this._beaters={};this._isStart=!1;this._autoStart="autoStart"in a?a.autoStart:!0;this._interval=a.interval||this.$static.DEFAULT_INTERVAL;this._maxInterval=a.maxInterval||this.$static.DEFAULT_MAX_INTERVAL},checkBeater:function(){var a=0,b;for(b in this._beaters)a+=this._beaters[b];return!!a},add:function(a,b,d){if(b%this._interval)b=
Math.round(b/this._interval)*this._interval;else if(b<this._interval)b=this._interval;else if(b>this._maxInterval)b=this._maxInterval;if(this._triggers[a])throw Error("beater is exist");this._beaters[b]=this._beaters[b]||0;this._triggers[a]={time:b,func:d};c.message.on(this,"Beater-"+b,d);this._beaters[b]++;!this._isStart&&this._autoStart&&this.start();return!0},remove:function(a){var b=this._triggers[a];if(!b)return!1;var d="Beater-"+b.time;this._beaters[b.time]--;this._triggers[a]=null;delete this._triggers[a];
c.message.off(this,d,b.func);this.checkBeater()||this.stop();return!0},start:function(){if(this._isStart)return!1;var a=this,b=0,d=this._interval;this._timer=setInterval(function(){b+=d;b>=a._maxInterval&&(b=0);var e,f;for(f in a._beaters)a._beaters[f]&&(e=Number(f),b%e||c.message.notify(a,"Beater-"+e,{time:e}))},d);return this._isStart=!0},stop:function(){if(!this._isStart)return!1;clearInterval(this._timer);this._timer=0;this._isStart=!1;return!0}})});
Z.$package("Z.util",["Z.message","Z.array"],function(c){this.Collection=new c.$class({name:"Collection"},{init:function(a){function b(){d.setModify()}a=a||{};this._keyName=a.keyName||"id";this._arr=[];this._map={};this._modifyTime=0;var d=this;c.message.on(this,"add",b);c.message.on(this,"remove",b);c.message.on(this,"clear",b);c.message.on(this,"update",b)},setModify:function(){this._modifyTime=+new Date},getModify:function(){return this._modifyTime},getByKey:function(a){return this.get(a)},getByIndex:function(a){return this.index(a)},
getIndexByKey:function(a,b){b=b||this._keyName;if(this._map[a])for(var c in this._arr)if(this._arr[c][b]==a)return c;return null},getKeyByIndex:function(a,b){var b=b||this._keyName,c=this.getByIndex(a);return c?c[b]:null},get:function(a){return this._map[a]},index:function(a){return this._arr[a]},getRange:function(a,b){return this._arr.slice(a,a+b)},filter:function(a,b){return c.array.filter(this._arr,a,b)},add:function(a,b,d){if(this._map[a[this._keyName]])return!1;this._map[a[this._keyName]]=a;
c.isUndefined(b)?(b=this._arr.length,this._arr.push(a)):this._arr.splice(b,0,a);d||c.message.notify(this,"add",{items:[a],index:b});return a},addRange:function(a,b,d){var e=[],f,g=this._keyName,h;for(h in a)f=a[h],this._map[f[g]]||(e.push(f),this._map[f[g]]=f);if(!e.length)return!1;c.isUndefined(b)?(b=this._arr.length,this._arr=this._arr.concat(e)):(a=[b,0].concat(e),Array.prototype.splice.apply(this._arr,a));d||c.message.notify(this,"add",{items:e,index:b});return e},removeByKey:function(a,b){var d=
this._map[a];if(d){var e=this.getIndexByKey(a);this._arr.splice(e,1);delete this._map[a];b||c.message.notify(this,"remove",{items:[d],index:e,key:a});return d}return!1},removeByIndex:function(a,b){var d=this._arr[a];return d?(this._arr.splice(a,1),delete this._map[d[this._keyName]],b||c.message.notify(this,"remove",{items:[d],index:a,key:d[this._keyName]}),d):!1},remove:function(a){return this.removeByKey(a)},removeRange:function(a,b){var d=[],e,f=this._keyName,g;for(g in a)e=a[g],this.removeByKey(e[f],
!0)&&d.push(e);if(!d.length)return!1;b||c.message.notify(this,"remove",{items:d});return d},update:function(a,b){var d=this.get(a.id);return d?(c.merge(d,a),b||c.message.notify(this,"update",{items:[d]}),d):!1},updateRange:function(a){var b=[],d,e;for(e in a)(d=this.update(a[e],!0))&&b.push(d);b.length&&c.message.notify(this,"update",{items:[b]});return!1},length:function(){return this._arr.length},clear:function(a){var b=this._arr;this._arr=[];this._map={};a||c.message.notify(this,"clear",{items:b})},
getFirst:function(){return this.index(0)},getLast:function(){return this.index(this.length()-1)},getAll:function(){return this.getRange(0,this.length())},each:function(a){for(var b=0,c;c=this._arr[b];b++)a(c,b)},exist:function(a){return!!this.get(a)}})});Z.$package("Z.util",function(){this.debounce=function(c,a,b){var d;return function(){if(!d||+new Date-d>c)b?a():setTimeout(a,c),d=+new Date}}});
Z.$package("Z.util",function(){var c={};this.delay=function(a,b,d,e){var f=arguments,g=0;1===f.length?(d=a,b=0,a=null):2===f.length&&(d=b,b=a,a=null);b=b||0;a&&b?(a in c&&(window.clearTimeout(c[a]),g=1),f=window.setTimeout(function(){c[a]=0;delete c[a];d.apply(e||window,[a])},b),c[a]=f):e?window.setTimeout(function(){d.apply(e||window)},b):window.setTimeout(d,b);return g};this.clearDelay=function(a){return a in c?(window.clearTimeout(c[a]),c[a]=0,delete c[a],0):2}});
Z.$package("Z.util",function(c){this.DependentQueue=new c.$class({name:"DependentQueue",statics:{STATUS_INIT:1,STATUS_RUNNING:2,STATUS_PAUSE:3,STATUS_STOP:4}},{init:function(a){a=a||{};this._onFinish=a.onFinish;this._onPause=a.onPause;this._onStop=a.onStop;this._currentIndex=-1;this._items=[];this._status=this.$static.STATUS_INIT},add:function(a){if(this.isRunning())return!1;this._items.push(a);return!0},isRunning:function(){return this._status===this.$static.STATUS_RUNNING},run:function(){if(this.isRunning()||
0>=this._items.length||this._currentIndex>=this._items.length-1)return!1;this._status=this.$static.STATUS_RUNNING;this.next()},reRun:function(){this._currentIndex--;this.next()},next:function(){this._currentIndex++;var a=this._items[this._currentIndex];a?a.exec(this,a):this._onFinish&&this._onFinish(this)},pause:function(){this._status=this.$static.STATUS_PAUSE;this._onPause&&this._onPause(this,this._items[this._currentIndex])},stop:function(){this._status=this.$static.STATUS_STOP;this._onStop&&this._onStop(this,
this._items[this._currentIndex])}})});
Z.$package("Z.util",["Z.message","Z.string","Z.util"],function(c){this.HttpRequest=new c.$class({init:function(a){this._require=a.require;this._requestCollection=new c.util.Collection({keyName:"id"})},require:function(a,b,d){var e=c.string.toQueryString(b.data),f;f=-1==a.indexOf("?")?a+"?"+e:a+"&"+e;var d=d||{},g=b.onSuccess,h=b.onError,k=b.onTimeout;if(e=this._requestCollection.get(f)){if("loading"===e.status)return!1;if(d.cacheTime&&e.responseTime-e.requireTime<d.cacheTime)return a=b.context||window,
g&&g.call(a,e.response),!0;this._requestCollection.remove(f)}var j={id:f,param:b,requireTime:+new Date,status:"loading"};this._requestCollection.add(j);b.onSuccess=function(a){d.cacheTime?(j.responseTime=+new Date,j.status="loaded",j.response=a):this._requestCollection.remove(f);var c=b.context||window;g&&g.call(c,a)};b.onError=function(a){this._requestCollection.remove(f);var c=b.context||window;h&&h.call(c,a)};b.onTimeout=function(a){this._requestCollection.remove(f);var c=b.context||window;k&&
k.call(c,a)};this._require(a,b)}})});Z.$package("Z.util",function(){var c={};this.loop=function(a,b,d,e){var f=0;2==arguments.length&&(d=b,b=a);b=b||0;if(a&&b){a in c&&(window.clearInterval(c[a]),f=1);var g=window.setInterval(function(){d.apply(e||window,[a])},b);c[a]=g}else setInterval(d,b);return f};this.clearLoop=function(a){return a in c?(window.clearInterval(c[a]),c[a]=0,delete c[a],0):2}});
Z.$package("Z.util",function(c){this.timeTaken=function(a){var b=">>>",d,e;2===arguments.length?"function"===typeof arguments[1]?e=arguments[1]:b='"'+arguments[1]+'"':3===arguments.length&&(d=arguments[1],e=arguments[2]);c.debug(b+" time test start.");d&&d();d=+new Date;a();d=+new Date-d;e&&e(d);c.debug(b+" time test end. time taken: "+d)}});
