(function(d){var i={UNDEFINED:0,BUILDED:1,LOADED:2,INITED:3},k={},l={},a=0,h=function(c){if(k[c])return k[c];var c=c.split("."),b=window,a;for(a in c){if(!(c[a]in b))return d;b=b[c[a]]}return b},g=function(c){return(c=h(c))?c.packageStatus:i.UNDEFINED},b=function(c,a,g){"string"===typeof c&&(c=h(c));var j={},f=h("Z");if(a)for(var d in a)j[d]=h(a[d]);g&&g.call(c,f,j);c.packageStatus=i.INITED;c=c.packageName;if(a=l[c]){for(j=0;j<a.length;j++)g=a[j],e(g.requirePackages)&&b(g.packageName,g.requirePackages,
g.constructor);delete l[c]}},e=function(c){if(!c)return!0;var b,a;for(a in c)if(b=c[a],g(b)!==i.INITED)return!1;return!0},f=function(){var c,g,h;c=arguments[0];3===arguments.length?(g=arguments[1],h=arguments[2]):2===arguments.length?h=arguments[1]:(c="Z.anonymous."+a++,h=arguments[0]);var j;j=c;var f=k[j];if(!f){var f=window,d=j.split("."),o;for(o in d)d[o]in f||(f[d[o]]={}),f=f[d[o]];k[j]=f}if(!("packageName"in f))f.packageName=j;if(!("packageStatus"in f))f.packageStatus=i.BUILDED;j=f;if(j.packageStatus===
i.BUILDED)j.packageStatus=i.LOADED;if(g&&!e(g))for(var p in g)j=g[p],l[j]||(l[j]=[]),l[j].push({packageName:c,requirePackages:g,constructor:h});else b(j,g,h)};f("Z",function(b){b.PACKAGE_STATUS=i;b.$package=f;b.getPackage=h;b.getPackageStatus=g})})();
Z.$package("Z",function(d){this.debug=function(a){window.console&&(console.debug?console.debug(a):console.log(a))};var i=Object.prototype.toString;this.is=function(a,h){var g=i.call(h).slice(8,-1);return void 0!==h&&null!==h&&g===a};this.isString=function(a){return"[object String]"===i.call(a)};this.isArray=Array.isArray||function(a){return"[object Array]"===i.call(a)};this.isArguments=function(a){return"[object Arguments]"===i.call(a)};this.isObject=function(a){return"[object Object]"===i.call(a)};
this.isFunction=function(a){return"[object Function]"===i.call(a)};this.isUndefined=function(a){return"[object Undefined]"===i.call(a)};this.isEmpty=function(a){if(a){if(this.isArray(a))return!!a.length;for(var h in a)return!1;return!0}return!1};var k=function(a,h,g){for(var b=arguments,e,f=1;f<b.length;f++){e=b[f];for(var c in e)a[c]=d.isArray(e[c])?e[c].concat():d.isObject(e[c])?a[c]&&d.isArray(a[c])?k({},e[c]):k({},a[c],e[c]):e[c]}return a},l=function(a){if(d.isArray(a))return a.concat();if(d.isArguments(a)){for(var h=
[],g=0,b;b=a[g];g++)h.push(l(b));return h}if(d.isObject(a))return k({},a);throw Error("the argument isn't an object or array");};this.merge=k;this.duplicate=l;this.extend=function(a,h){k(a,h);a.prototype=k({},h.prototype,a.prototype);a.prototype.constructor=a}});
Z.$package("Z",function(d){var i=function(){},k=function(a,g){1===arguments.length&&(g=a,a={});g=g||{};if(!d.isFunction(g.init))g.init=i;var b=function(){return this.init.apply(this,arguments)},e=a.extend;if(e){if("interface"===e.type&&d.isArray(e.methods)&&d.isFunction(e.checkImplements))throw Error("can not extend a interface!");var f=e.prototype.init,c=g.init,n=d.duplicate(e.prototype);delete n.init;var e=b.prototype=d.merge({},e.prototype,g),m;for(m in n)d.isFunction(n[m])&&d.isFunction(e[m])&&
(e[m]=function(b,a){return function(){var c=this.$super;this.$super=b;a.apply(this,arguments);this.$super=c}}(n[m],e[m]));b.prototype.init=function(){var a=d.duplicate(arguments);f.apply(this,a);this.$static=b;c.apply(this,arguments)}}else c=g.init,b.prototype=g,b.prototype.init=function(){this.$static=b;c.apply(this,arguments)};b.prototype.constructor=b;b.type="class";b.className=a.name||"anonymous";if(n=a["implements"]){m=[];for(var j in n)e=n[j].checkImplements(b.prototype),m=m.concat(e);if(m.length)throw Error("the '"+
b.className+"' class hasn't implemented the interfaces's methods . ["+m+"]");}a.statics&&d.merge(b,a.statics);return b},l=function(a){var g=[],b,e;for(e in this.methods)b=a[this.methods[e]],(!b||!d.isFunction(b))&&g.push(methods[e]);return g},a=function(a,g){1===arguments.length&&(g=a,a={});var b=function(){throw Error("the interface can not be Instantiated!");};b.type="interface";b.interfaceName=a.name||"anonymous";b.methods=g;b.checkImplements=l;return b};this.define=function(d,g,b){var e=Array.prototype.slice.call(arguments,
1);if("class"===d)return k.apply(this,e);if("interface"===d)return a.apply(this,e)};this.$class=k;this.$interface=a});
Z.$package("Z.message",function(d){var i,k=0,l=function(){if(!i&&(i=document.createElement("div"),!document.createEvent))i.style.cssText="position: absolute; top: -9999em; left: -9999em; width: 0px; height: 0px;",document.body.appendChild(i);return i},a=function(a,b,e){var f,c,d,h;if(2>arguments.length)throw Error("addListener arguments not enough");2===arguments.length&&(e=b,b=a,a=window);if(!a.__listeners)a.__listeners={},a.__listenerId=+new Date+""+k++;d=a.__listeners;h=a.__listenerId;if(d[b])for(c in d[b]){if(f=
d[b][c],f.func===e)return!1}else d[b]=[];c=l();c.addEventListener?(f=function(a){e.apply(window,a.params)},c.addEventListener(h+"-"+b,f,!1)):(f=function(a){var a=window.event,c=a.params.pop();b===a.params[1]&&c===h&&e.apply(window,a.params)},c.attachEvent("onpropertychange",f));f={func:e,wrapFunc:f};d[b].push(f);return!0},h=function(a,b,e){var f,c,d,h;if(2>arguments.length)throw Error("removeListener arguments not enough");2===arguments.length&&(e=b,b=a,a=window);d=a.__listeners;h=a.__listenerId;
if(!d||!d[b])return!1;c=l();for(var j in d[b])if(f=d[b][j],f.func===e)return d[b].slice(j,1),c.removeEventListener?c.removeEventListener(h+"-"+b,f.wrapFunc,!1):c.detachEvent("onpropertychange",f.wrapFunc),!0;return!1};this.on=this.addListener=a;this.off=this.removeListener=h;this.notify=function(a,b,e){var f,c,h,i;1===arguments.length?(b=a,a=window):2===arguments.length&&d.isString(a)&&(e=b,b=a,a=window);d.debug("notify message: "+b);h=a.__listeners;i=a.__listenerId;if(!h||!h[b])return!1;f=l();document.createEvent?
(c=document.createEvent("Events"),c.initEvent(i+"-"+b,!1,!1),c.params=[e,b],f.dispatchEvent(c)):(c=document.createEventObject("onpropertychange"),c.params=[e,b,i],f.fireEvent("onpropertychange",c));return 0!==h[b].length}});
