(function(g){var i={UNDEFINED:0,BUILDED:1,LOADED:2,INITED:3},l={},j={},m=function(){},k=function(a){if(l[a])return l[a];var a=a.split("."),b=window,d;for(d in a){if(!(a[d]in b))return g;b=b[a[d]]}return b},f=function(a){return(a=k(a))?a.packageStatus:i.UNDEFINED},e=function(a,b,c){"string"===typeof a&&(a=k(a));var h={},f=k("Z");if(b)for(var g in b)h[g]=k(b[g]);c&&c.call(a,f,h);a.packageStatus=i.INITED;a=a.packageName;if(b=j[a]){for(h=0;h<b.length;h++)c=b[h],d(c.requirePackages)&&e(c.packageName,c.requirePackages,
c.constructor);delete j[a]}},d=function(a){if(!a)return!0;var b,c;for(c in a)if(b=a[c],f(b)!==i.INITED)return!1;return!0},c=function(){var a,b,c;a=arguments[0];3===arguments.length?(b=arguments[1],c=arguments[2]):c=arguments[1];var h;h=l[a];if(!h){h=window;var g=a.split("."),f;for(f in g)g[f]in h||(h[g[f]]={}),h=h[g[f]];l[a]=h}if(!("packageName"in h))h.packageName=a;if(!("packageStatus"in h))h.packageStatus=i.BUILDED;if(h.packageStatus===i.BUILDED)h.packageStatus=i.LOADED;if(b&&!d(b))for(var k in b)h=
b[k],j[h]||(j[h]=[]),j[h].push({packageName:a,requirePackages:b,constructor:c});else e(h,b,c)};c("Z",function(a){a.debug=m;a.PACKAGE_STATUS=i;a.$package=c;a.getPackage=k;a.getPackageStatus=f})})();
Z.$package("Z",function(){var g=Object.prototype.toString;this.isString=function(i){return"[object String]"===g.call(i)};this.isArray=Array.isArray||function(i){return"[object Array]"===g.call(i)};this.isArguments=function(i){return"[object Arguments]"===g.call(i)};this.isObject=function(i){return"[object Object]"===g.call(i)};this.isFunction=function(i){return"[object Function]"===g.call(i)};this.isUndefined=function(i){return"[object Undefined]"===g.call(i)}});
Z.$package("Z",function(g){var i=function(){},l=function(d,c,a){for(var b=arguments,e,h=1;h<b.length;h++){e=b[h];for(var f in e)d[f]=g.isArray(e[f])?e[f].concat():g.isObject(e[f])?d[f]&&g.isArray(d[f])?l({},e[f]):l({},d[f],e[f]):e[f]}return d},j=function(d){if(g.isArray(d))return d.concat();if(g.isArguments(d)){for(var c=[],a=0,b;b=d[a];a++)c.push(j(b));return c}if(g.isObject(d))return l({},d);throw Error("the argument isn't an object or array");},m=function(){return this.className},k=function(d,
c){1===arguments.length&&(c=d,d={});c=c||{};if(!g.isFunction(c.init))c.init=i;var a=function(){g.debug("class ["+a.className+"] init");return this.init.apply(this,arguments)},b=d.extend;if(b){if("interface"===b.type&&g.isArray(b.methods)&&g.isFunction(b.checkImplements))throw Error("can not extend a interface!");var f=b.prototype.init,h=c.init,e=j(b.prototype);delete e.init;a.prototype=l({},b.prototype,c);var k=c;a.prototype.init=function(){var b=j(arguments);f.apply(this,b);this.$static=a;b=j(arguments);
h.apply(this,b);var c=this;this.$super={};for(var d in e)g.isFunction(e[d])&&k[d]&&(this.$super[d]=function(a){return function(){e[a].apply(c,arguments)}}(d))}}else h=c.init,a.prototype=c,a.prototype.init=function(){this.$static=a;h.apply(this,arguments)};a.type="class";a.className=d.name||"anonymous";a.toString=m;if(b=d["implements"]){var n=[],o,p;for(p in b)o=b[p].checkImplements(a.prototype),n=n.concat(o);if(n.length)throw Error("the '"+a.className+"' class hasn't implemented the interfaces's methods . ["+
n+"]");}d.statics&&l(a,d.statics);return a},f=function(d){var c=[],a,b;for(b in this.methods)a=d[this.methods[b]],(!a||!g.isFunction(a))&&c.push(methods[b]);return c},e=function(d,c){1===arguments.length&&(c=d,d={});var a=function(){throw Error("the interface can not be Instantiated!");};a.type="interface";a.interfaceName=d.name||"anonymous";a.methods=c;a.checkImplements=f;return a};this.merge=l;this.duplicate=j;this.define=function(d,c,a){var b=Array.prototype.slice.call(arguments,1);if("class"===
d)return k.apply(this,b);if("interface"===d)return e.apply(this,b)};this.$class=k;this.$interface=e});
Z.$package("Z.message",function(g){var i,l=0,j=function(){if(!i&&(i=document.createElement("div"),!document.createEvent))i.style.cssText="position: absolute; top: -9999em; left: -9999em; width: 0px; height: 0px;",document.body.appendChild(i);return i},m=function(f,e,d){var c,a,b,g;if(2>arguments.length)throw Error("addListener arguments not enough");2===arguments.length&&(d=e,e=f,f=window);if(!f.__listeners)f.__listeners={},f.__listenerId=+new Date+""+l++;b=f.__listeners;g=f.__listenerId;if(b[e])for(a in b[e]){if(c=
b[e][a],c.func===d)return!1}else b[e]=[];a=j();a.addEventListener?(c=function(a){d.apply(window,a.params)},a.addEventListener(g+"-"+e,c,!1)):(c=function(a){var a=window.event,b=a.params.pop();e===a.params[1]&&b===g&&d.apply(window,a.params)},a.attachEvent("onpropertychange",c));c={func:d,wrapFunc:c};b[e].push(c);return!0},k=function(f,e,d){var c,a,b,g;if(2>arguments.length)throw Error("removeListener arguments not enough");2===arguments.length&&(d=e,e=f,f=window);b=f.__listeners;g=f.__listenerId;
if(!b||!b[e])return!1;a=j();for(var h in b[e])if(c=b[e][h],c.func===d)return b[e].slice(h,1),a.removeEventListener?a.removeEventListener(g+"-"+e,c.wrapFunc,!1):a.detachEvent("onpropertychange",c.wrapFunc),!0;return!1};this.on=this.addListener=m;this.off=this.removeListener=k;this.notify=function(f,e,d){var c,a,b,i;1===arguments.length?(e=f,f=window):2===arguments.length&&g.isString(f)&&(d=e,e=f,f=window);g.debug("notify message: "+e);b=f.__listeners;i=f.__listenerId;if(!b||!b[e])return!1;c=j();document.createEvent?
(a=document.createEvent("Events"),a.initEvent(i+"-"+e,!1,!1),a.params=[d,e],c.dispatchEvent(a)):(a=document.createEventObject("onpropertychange"),a.params=[d,e,i],c.fireEvent("onpropertychange",a));return 0!==b[e].length}});
